openapi: 3.0.3
info:
  title: CheckUpdatePlatform
  description: API дипломного проекта на тему "Платформа по отслеживанию обновлений веб-ресурсов"
  contact:
    email: victor_k02@mail.ru
    name: Victor Kochnev
    url: https://vk.com/laym0n
  version: 1.0.0
paths:
  /stub:
    post:
      summary: Заглушка для генерации кода
      responses:
        '200':
          description: Заглушка для генерации кода
components:
  schemas:
    UserRegistrationRequestDto:
      type: object
      properties:
        email:
          type: string
          description: email для регистрации
          format: email
        password:
          type: string
          description: Пароль
      required:
        - email
        - password
    ErrorMessageDto:
      description: Сообщение с ошибкой
      properties:
        message:
          type: string
      required:
        - message
